try:
    print(a)
except:
  # eror akan menampilkan ini karena fungsi try untuk menganalisis program apakah ada kesalahan
  # karena di dalam try variabel a tidak ada maka akan masuk ke except
    print('maaf program ada yang eror')
